fixed capture script

diff --git a/bin/capture-to-inbox b/bin/capture-to-inbox
--- a/bin/capture-to-inbox
+++ b/bin/capture-to-inbox
@@ -3,18 +3,31 @@
 # A script to capture text into my inbox file
 INBOX_FILE=~/notes_repo/inbox.txt
 
+function die() {
+    echo "$*" 1>&2 ;
+    notify-send "$*"
+    exit 1;
+}
+
 # zenity is the program used to capture input -- make sure it's installed
 if ! which zenity; then
-    notify-send "ERROR: Cannot capture inbox item! zenity not installed"
-    exit 1
+    die "ERROR: Cannot capture inbox item! zenity not installed"
 fi
 
 RESPONSE=$(zenity --entry --title "Capture to inbox" --text "What would you like to capture?")
 RETCODE=$?
 
-if [ $RETCODE ] || [ -z "$RESPONSE" ]; then
+if [ $RETCODE -ne 0 ] || [ -z "$RESPONSE" ]; then
     # nothing to capture
+    echo "Nothing to capture"
     exit 0
 fi
 
+echo $RESPONSE
 echo $RESPONSE >> $INBOX_FILE
+
+# sanity check
+LAST_LINE=$(tail -n 1 $INBOX_FILE)
+if [ "$LAST_LINE" != "$RESPONSE" ]; then
+    die "ERROR: capture failed! line not found"
+fi
