Make watson_wrapper work without X server

diff --git a/bin/watson_wrapper b/bin/watson_wrapper
--- a/bin/watson_wrapper
+++ b/bin/watson_wrapper
@@ -19,10 +19,21 @@ if [ -z "$WATSON" ]; then
     fi
 fi
 
-ROFI=$(which rofi)
-if [ -z "$ROFI" ]; then
-    die "rofi not found"
+# Specify which "choose" program to use, depending on environment
+# TODO allow to type a new value not in the choice list?
+CHOOSE_APP_NAME=rofi
+CHOOSE_APP_ARGS="-dmenu"
+if ! xset q &>/dev/null; then
+    # No X server running: use fzf in termnal
+    CHOOSE_APP_NAME=fzf
+    CHOOSE_APP_ARGS=
 fi
+# Verify that it is installed and available in the PATH
+CHOOSE=$(which $CHOOSE_APP_NAME)
+if [ -z "$CHOOSE" ]; then
+    die "$CHOOSE_APP_NAME not found"
+fi
+CHOOSE="$CHOOSE $CHOOSE_APP_ARGS"
 
 # When invoked without arguments, the behavior depends on current state:
 # 1) If a project is currently being tracked, stop it.
@@ -35,7 +46,7 @@ if [ $# -eq 0 ]; then
         notify-send "$STOP_OUTPUT"
     else
         # TODO cannot add tags
-        NEW_PROJECT=$($WATSON projects | $ROFI -dmenu)
+        NEW_PROJECT=$($WATSON projects | $CHOOSE)
         # Rofi returned non-zero: probably nothing picked (Esc or Ctrl+C)
         [ $? -eq 0 ] || exit 0
         # Start new project
